# Generated by Django 4.2.7 on 2024-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='other_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prediction',
            name='landcover_plot',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='ndvi_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='ndvi_ndwi_plot',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
