# Generated by Django 4.2.7 on 2024-01-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
